Prevent passing out an undefined reference to scatter/gather interface.
For not loadbalanced grid the dereferenced pointer was null. While test
was working it is an error nevertheless. Fixed by initially using an
empty interface.