Move cells of wells correctly if multiple wells perforate the same cell.
Previously, we only moved the perforated cells of one well to the new
partition. In the case that a cell was also perforated by another cell
we might have moved only a few cells of that other well. The rest
would remain where they were previously. Hence the well might (still)
be distributed between multiple processors and the user would see the
following exception:
```
Error: [opm/grid/common/ZoltanPartition.cpp:132] Well is distributed between processes, which should not be the case!
```

To solve this problem we now make a breadth first search in the well
graph starting with a cell of the well to be moved. This will
effective move the cells of all wells whose cells are reachable via
the well graph. As a result there should be no distributed wells,
anymore.